# Generated by Django 5.2.8 on 2025-11-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0003_todo_remove_itemimage_item_delete_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='steps',
            field=models.JSONField(default=0),
        ),
    ]
